import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import './globals.scss'
import { Inter } from 'next/font/google'
import Footer from "../components/Footer";
import Header from "../components/Header";
import Image from "next/image";
import youtubeImg from "./../public/youTube.png"
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Anek+Telugu:wght@600&family=Montserrat:wght@300&family=Poppins&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.0/css/all.css" />
      </Head>
      <body className={inter.className}>
        <Header />
          {children}
        <Image
        src={youtubeImg}
        width={500}
        height={350}
        alt="preview"
        placeholder="blur"
        />
        <Footer />
      </body>
    </html>
  )
}
